---
# This workflow will build a Java project with Maven
name: build

on:
  push:
    branches: [main, "[0-9]+.[0-9]+-SNAPSHOT"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.12.1
        continue-on-error: true  # for act
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: beng-nexus
      - name: Build and deploy with Maven
        run: |
          (cd src/main/java; mv module-info.java module-info.java.not)
          mvn generate-sources -Ddelombok.skip=false
          (cd src/main/java; mv module-info.java.not module-info.java)
          cp -f src/main/java/module-info.java target/delombok
          mvn -Pdeploy -B test install
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          files: "target/surefire-reports/*.xml"


