---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
          cache: maven
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.2
        with:
          global: true
          name: 'github'
          email: 'github@meeuw.org'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: |
          mvn --batch-mode release:prepare
          (cd src/main/java; mv module-info.java module-info.java.not)
          mvn generate-sources -Ddelombok.skip=false
          (cd src/main/java; mv module-info.java.not module-info.java)
          cp -f src/main/java/module-info.java target/delombok
          mvn -Pdeploy --batch-mode  -Darguments=-DskipTests  release:perform
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
